const uiStyle=document.createElement('style');uiStyle.textContent=`.catalog-panel{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:0 0 18px}.catalog-panel>div{background:#0b1827;border:1px solid #1a2c40;border-radius:9px;padding:10px 12px}.catalog-panel b{display:block;font-size:12px;color:#dfe8f1}.catalog-panel span{display:block;color:#6d8197;font-size:10px;margin-top:3px}.stat-strip{display:none}@media(max-width:700px){.catalog-panel{grid-template-columns:1fr 1fr}.hero-line p{font-size:13px}.map{height:300px}}`;document.head.appendChild(uiStyle);
const $=s=>document.querySelector(s);const views=['explorer','timeline','relations','discover','hypotheses'];const titles={explorer:'NORA',timeline:'Evolución',relations:'Relaciones',discover:'Descubrimientos',hypotheses:'Hipótesis'};let selectedCell=null;
function show(v){views.forEach(x=>document.getElementById(x)?.classList.toggle('active-view',x===v));document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===v));$('#page-title').textContent=titles[v];window.scrollTo({top:0,behavior:'smooth'});if(v==='discover')loadDiscovery();if(v==='relations')runRelations()}
document.addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(b)show(b.dataset.view)});
const meta={ndvi:['VEGETACIÓN','NDVI · intensidad relativa','NDVI'],precip:['AGUA','Precipitación · anomalía','mm'],temp:['CLIMA','Temperatura · anomalía','°C'],water:['AGUA','Agua · disponibilidad','fracción'],fire:['PERTURBACIÓN','Fuego · fracción quemada','fracción']};
async function api(mode,params={}){const q=new URLSearchParams({mode,...params});const r=await fetch('/api/nora?'+q);if(!r.ok)throw new Error(await r.text());return r.json()}
function setStatus(ok,text){$('#data-status').textContent=text;$('#data-source').textContent=ok?'fuente real':'modo local';$('#data-badge').textContent=ok?'DATOS REALES':'SIN DATOS'}
function fallbackMap(){const map=$('#map');map.innerHTML='';for(let i=0;i<280;i++){const c=document.createElement('div');c.className='cell';c.style.background=`rgba(45,145,95,${.2+((Math.sin(i*7.31)+1)/2)*.6})`;c.title=`Zona ${i+1}`;c.onclick=()=>selectCell(i);map.appendChild(c)}}
function renderMap(rows){const map=$('#map');map.innerHTML='';const variable=$('#variable').value,key={ndvi:'ndvi',precip:'precip_mm',temp:'temp_c',water:'water_fraction',fire:'burned_fraction'}[variable],vals=rows.map(r=>Number(r[key])).filter(Number.isFinite),min=Math.min(...vals),max=Math.max(...vals);rows.forEach(r=>{const c=document.createElement('div');c.className='cell';const raw=Number(r[key]),v=Number.isFinite(raw)&&max>min?(raw-min)/(max-min):.2;c.style.background=`rgba(${variable==='fire'?190:variable==='temp'?210:variable==='precip'?55:45},${variable==='fire'?70:variable==='temp'?115:variable==='precip'?125:145},${variable==='ndvi'?85:variable==='water'?160:variable==='precip'?190:55},${.16+v*.72})`;c.title=`Zona ${r.cell_id} · ${Number.isFinite(raw)?raw.toFixed(3):'sin dato'}`;c.onclick=()=>selectCell(r.cell_id);map.appendChild(c)})}
async function loadMap(){try{const d=await api('map',{variable:$('#variable').value,period:$('#period').value});renderMap(d.rows);$('#map-date').textContent=d.date||'—';$('#stat-cells').textContent=(d.cell_count||d.rows.length).toLocaleString('es-ES');$('#stat-rows').textContent=(d.total_rows||'—').toLocaleString('es-ES');setStatus(true,'datos reales · Supabase');$('#data-source').textContent=`${d.variables||9} variables catalogadas`}catch(e){fallbackMap();setStatus(false,'API no disponible');$('#map-date').textContent='sin conexión'}}
async function loadCatalog(){try{const d=await api('catalog');const host=$('#explorer .hero-line');if(host&&!$('#catalog-panel')){const p=document.createElement('div');p.id='catalog-panel';p.className='catalog-panel';p.innerHTML=`<div><b>${d.variables.length} variables</b><span>fuentes catalogadas</span></div>`+d.variables.slice(0,6).map(v=>`<div><b>${v.name}</b><span>${v.source}</span></div>`).join('');host.after(p)}}catch(e){}}
async function selectCell(id){selectedCell=id;$('#cell-title').textContent=`Zona ${id}`;$('#timeline-cell').textContent=`Zona ${id}`;try{const d=await api('cell',{cell_id:id});const last=d.rows[d.rows.length-1]||{};$('#score').textContent=fmt(last.ndvi,2);$('#score-unit').textContent='NDVI';$('#cell-rain').textContent=fmt(last.precip_mm,0);$('#cell-temp').textContent=fmt(last.temp_c,1);$('#cell-water').textContent=fmt(last.water_fraction,2);$('#cell-fire').textContent=fmt(last.burned_fraction,3);$('#local-relation').textContent=d.relation?.label||'Analizar relación';$('#local-r').textContent=d.relation?.r!=null?`r = ${d.relation.r.toFixed(2)} · ${d.relation.lag} meses`:'—';$('#trend-label').textContent=d.trend?.label||'calculando';drawSpark(d.rows);drawTimeline(d.rows);show('timeline')}catch(e){show('timeline')}}
function fmt(x,n=2){return Number.isFinite(Number(x))?Number(x).toFixed(n):'—'}
function drawSpark(rows){const s=$('#spark');s.innerHTML='';const vals=rows.map(x=>Number(x.ndvi)).filter(Number.isFinite);if(!vals.length)return;const min=Math.min(...vals),max=Math.max(...vals);vals.forEach(v=>{const i=document.createElement('i');i.style.height=`${18+((v-min)/(max-min||1))*70}%`;s.appendChild(i)})}
function drawTimeline(rows){const box=$('#timeline-chart');box.innerHTML='';const vals=rows.map(x=>Number(x.ndvi)),valid=vals.filter(Number.isFinite);if(!valid.length)return;const min=Math.min(...valid),max=Math.max(...valid);rows.forEach(r=>{const n=Number(r.ndvi);if(!Number.isFinite(n))return;const i=document.createElement('i');i.style.height=`${10+((n-min)/(max-min||1))*82}%`;i.title=`${r.year}-${String(r.month).padStart(2,'0')}: ${n.toFixed(3)}`;box.appendChild(i)});const change=valid[valid.length-1]-valid[0];$('#timeline-insight').textContent=`NDVI ${change>=0?'↑':'↓'} ${Math.abs(change).toFixed(2)}`;$('#timeline-text').textContent='Cambio descriptivo. NORA debe controlar estacionalidad y variables de confusión antes de interpretar causalidad.'}
async function runRelations(){const target=$('#target').value,driver=$('#driver').value;$('#relation-title').textContent=`${label(driver)} → ${label(target)}`;try{const d=await api('relations',{target,driver,cell_id:selectedCell||''});drawRelations(d.lags||[]);$('#best-r').textContent=d.best?`r = ${d.best.r.toFixed(2)}`:'—';$('#best-text').textContent=d.best?`Retardo dominante: ${d.best.lag} meses · exploratorio`:'Sin resultado';$('#relation-confidence').textContent=d.sampled?`muestra ${d.cells} celdas`:'calculado'}catch(e){drawRelations([]);$('#best-r').textContent='—';$('#best-text').textContent='No se pudo calcular la relación.'}}
function drawRelations(vals){const box=$('#response-chart');box.innerHTML='';if(!vals.length)vals=[0,0,0,0,0,0,0];vals.forEach((v,i)=>{const b=document.createElement('i');b.style.height=`${10+Math.abs(v)*85}%`;if(i===vals.indexOf(Math.max(...vals)))b.className='peak';box.appendChild(b)});$('#relation-rows').innerHTML=[['Precipitación','NDVI'],['Temperatura','NDVI'],['Fuego','NDVI'],['Agua','NDVI']].map(x=>`<div class="rel-row"><b>${x[0]}</b><span>${x[1]}</span><strong>—</strong><i style="width:0%"></i><small>seleccionar</small></div>`).join('')}
function label(x){return {ndvi:'NDVI',precip:'Precipitación',temp:'Temperatura',water:'Agua',fire:'Fuego'}[x]||x}
async function loadDiscovery(){try{const d=await api('discover');$('#discovery-title').textContent=d.title;$('#discovery-copy').textContent=`${d.copy} Muestra: ${Number(d.sample_size||0).toLocaleString('es-ES')} observaciones.`;$('#dist-strong').textContent=d.distribution?.strong??'—';$('#dist-mid').textContent=d.distribution?.moderate??'—';$('#dist-weak').textContent=d.distribution?.weak??'—';$('#dist-neg').textContent=d.distribution?.negative??'—';$('#factors').innerHTML=(d.factors||[]).map(f=>`<div class="factor"><span>${f.name}</span><b>${f.value>0?'+':''}${Number(f.value).toFixed(2)}</b><i style="width:${Math.min(100,Math.abs(f.value)*100)}%"></i></div>`).join('');$('#hyp-evidence').textContent=d.evidence||'exploratorio';setStatus(true,'motor de descubrimiento activo')}catch(e){$('#discovery-title').textContent='Sin evidencia suficiente';$('#discovery-copy').textContent='NORA no presenta resultados inventados cuando no puede calcularlos.'}}
$('#variable')?.addEventListener('change',e=>{$('#map-kicker').textContent=meta[e.target.value][0];$('#map-title').textContent=meta[e.target.value][1];$('#score-unit').textContent=meta[e.target.value][2];loadMap()});$('#period')?.addEventListener('change',loadMap);$('#hotspots')?.addEventListener('click',e=>{const on=e.currentTarget.classList.toggle('on');e.currentTarget.textContent=on?'Ocultar hotspots':'Mostrar hotspots';document.querySelectorAll('.cell').forEach(c=>c.classList.toggle('hot',on))});$('#lag')?.addEventListener('input',e=>$('#lag-value').textContent=`${e.target.value} meses`);$('#run-relations')?.addEventListener('click',runRelations);$('#refresh-cell')?.addEventListener('click',()=>selectedCell&&selectCell(selectedCell));$('#target')?.addEventListener('change',runRelations);$('#driver')?.addEventListener('change',runRelations);loadMap();loadCatalog();loadDiscovery();