const $=s=>document.querySelector(s);const views=['explorer','timeline','relations','discover','hypotheses'];const titles={explorer:'Explorer',timeline:'Evolución',relations:'Relaciones',discover:'Descubrimientos',hypotheses:'Hipótesis'};let regionId='alto_xingu',selectedCell=null,customGeometry=null;
const labels={ndvi:'NDVI',precip:'Precipitación',temp:'Temperatura',water:'Agua',fire:'Fuego',soil_moisture_rootzone:'Humedad suelo',lai:'LAI',gpp:'GPP',surface_radiation_wm2:'Radiación solar',wind_speed_ms:'Viento'};
const api=async(mode,p={})=>{const r=await fetch('/api/nora?'+new URLSearchParams({mode,...p}));if(!r.ok)throw Error(await r.text());return r.json()};
function show(v){views.forEach(x=>document.getElementById(x)?.classList.toggle('active-view',x===v));document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===v));$('#page-title').textContent=titles[v];window.scrollTo({top:0,behavior:'smooth'});if(v==='relations')runRelations();if(v==='discover')loadDiscovery()}
document.addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(b)show(b.dataset.view)});
function setStatus(real,text){$('#data-status').textContent=text;$('#data-badge').textContent=real?'DATOS REALES':'PREPARADO';$('#data-source').textContent=real?'fuente registrada':'sin ingesta'}
function empty(msg='Sin datos ingeridos'){const m=$('#map');m.innerHTML=`<div class="map-empty"><b>${msg}</b><span>NORA no rellena huecos con datos simulados.</span></div>`}
async function loadWorkspace(){try{const d=await api('workspace');$('#domain-chips').innerHTML=d.domains.map(x=>`<span>${x}</span>`).join('');$('#stat-domains').textContent=d.domains.length;const sel=$('#region');sel.innerHTML=`<option value="alto_xingu">Alto Xingu · piloto</option>`+d.regions.filter(r=>r.region_id!=='alto_xingu').map(r=>`<option value="${r.region_id}">${r.name}</option>`).join('')+`<option value="custom">Cualquier zona · coordenadas</option>`;sel.value=regionId}catch(e){$('#domain-chips').innerHTML='<span>registro no disponible</span>'}}
function bbox(){return customGeometry?{geometry:JSON.stringify(customGeometry)}:{}}
async function loadPlan(){try{const d=await api('plan',{region_id:regionId});$('#context-region').textContent=d.region?.name||'Zona personalizada';$('#map-area').textContent=d.region?.name||'Zona personalizada';$('#zone-status').textContent=d.ingested?'Datos listos':'Zona preparada';$('#zone-detail').textContent=d.ingested?'1.880 celdas · 288 meses':`${d.available?.length||0} variables registradas · ingesta pendiente`;$('#mission-stage').textContent=d.ingested?'6 · Mapeo y relaciones':'2 · Detectar variables';$('#mission-bar').style.width=d.ingested?'65%':'22%';$('#mission-state').textContent=d.objective_reached?'objetivo alcanzado':'objetivo aún no alcanzado';$('#data-plan-copy').textContent=d.ingested?'Datos del piloto disponibles. NORA puede validar, mapear y buscar relaciones.':'NORA ya sabe qué variables y fuentes puede buscar para esta zona. La recopilación se ejecutará automáticamente cuando el worker esté desplegado.';setStatus(d.ingested,d.ingested?'datos conectados':'zona lista');await loadMap()}catch(e){setStatus(false,'error de conexión');empty('No se pudo preparar la zona')}}
async function loadMap(){try{const d=await api('map',{region_id:regionId,variable:$('#variable').value,period:$('#period').value,...bbox()});if(!d.rows?.length){empty(d.message||'Zona preparada · sin datos todavía');$('#stat-cells').textContent='—';$('#stat-rows').textContent='—';$('#map-date').textContent='—';return}renderMap(d.rows);$('#map-date').textContent=d.date||'—';$('#stat-cells').textContent=d.cell_count.toLocaleString('es-ES');$('#stat-rows').textContent=d.total_rows.toLocaleString('es-ES');$('#stat-months').textContent=288}catch(e){empty('Error leyendo los datos')}}
function renderMap(rows){const m=$('#map');m.innerHTML='';const v=$('#variable').value,key={ndvi:'ndvi',precip:'precip_mm',temp:'temp_c',water:'water_fraction',fire:'burned_fraction'}[v]||v,vals=rows.map(r=>Number(r[key])).filter(Number.isFinite),min=Math.min(...vals),max=Math.max(...vals);rows.forEach(r=>{const c=document.createElement('button');c.className='cell';const n=Number(r[key]);const z=Number.isFinite(n)&&max>min?(n-min)/(max-min):.2;c.style.background=`rgba(70,${110+Math.round(z*100)},${95+Math.round(z*80)},${.2+z*.7})`;c.title=`Celda ${r.cell_id} · ${Number.isFinite(n)?n.toFixed(3):'sin dato'}`;c.onclick=()=>selectCell(r.cell_id);m.appendChild(c)})}
async function selectCell(id){selectedCell=id;$('#cell-title').textContent=`Zona ${id}`;$('#timeline-cell').textContent=`Zona ${id}`;try{const d=await api('cell',{region_id:regionId,cell_id:id});if(!d.rows.length){$('#local-relation').textContent='Sin datos';show('timeline');return}const last=d.rows.at(-1)||{};$('#score').textContent=fmt(last.ndvi);$('#cell-rain').textContent=fmt(last.precip_mm,0);$('#cell-temp').textContent=fmt(last.temp_c,1);$('#cell-water').textContent=fmt(last.water_fraction);$('#cell-fire').textContent=fmt(last.burned_fraction,3);$('#local-relation').textContent=d.relation?.label||'—';$('#local-r').textContent=d.relation?.r!=null?`r = ${d.relation.r.toFixed(2)} · ${d.relation.lag} meses`:'—';$('#trend-label').textContent=d.trend?.label||'—';drawSpark(d.rows);drawTimeline(d.rows);show('timeline')}catch(e){show('timeline')}}
const fmt=(x,n=2)=>Number.isFinite(Number(x))?Number(x).toFixed(n):'—';
function drawSpark(rows){const s=$('#spark');s.innerHTML='';const a=rows.map(r=>Number(r.ndvi)).filter(Number.isFinite),mi=Math.min(...a),ma=Math.max(...a);a.forEach(v=>{const i=document.createElement('i');i.style.height=`${15+((v-mi)/(ma-mi||1))*80}%`;s.appendChild(i)})}
function drawTimeline(rows){const box=$('#timeline-chart');box.innerHTML='';const a=rows.map(r=>Number(r.ndvi)).filter(Number.isFinite),mi=Math.min(...a),ma=Math.max(...a);rows.forEach(r=>{const n=Number(r.ndvi);if(!Number.isFinite(n))return;const i=document.createElement('i');i.style.height=`${10+((n-mi)/(ma-mi||1))*85}%`;i.title=`${r.year}-${String(r.month).padStart(2,'0')}: ${n.toFixed(3)}`;box.appendChild(i)});$('#timeline-insight').textContent=a.length>1?`NDVI ${a.at(-1)>=a[0]?'↑':'↓'} ${Math.abs(a.at(-1)-a[0]).toFixed(2)}`:'—';$('#timeline-text').textContent='Cambio descriptivo. NORA todavía debe controlar estacionalidad, confusores y robustez.'}
function label(x){return labels[x]||x}
async function runRelations(){const target=$('#target').value,driver=$('#driver').value;$('#relation-title').textContent=`${label(driver)} → ${label(target)}`;try{const d=await api('relations',{region_id:regionId,target,driver,cell_id:selectedCell||''});drawRelations(d.lags||[]);$('#best-r').textContent=d.best?`r = ${d.best.r.toFixed(2)}`:'—';$('#best-text').textContent=d.best?`Retardo dominante: ${d.best.lag} meses · exploratorio`:'Sin datos para esta zona';$('#relation-confidence').textContent=d.status==='ready'?`muestra ${d.cells} celdas`:'pendiente'}catch(e){drawRelations([])}}
function drawRelations(a){const box=$('#response-chart');box.innerHTML=a.length?a.map((v,i)=>`<i class="${i===a.indexOf(Math.max(...a))?'peak':''}" style="height:${10+Math.abs(v)*85}%"></i>`).join(''):'<div class="chart-empty">Sin datos para esta zona</div>';$('#relation-rows').innerHTML=[['Precipitación','NDVI'],['Temperatura','NDVI'],['Fuego','NDVI'],['Agua','NDVI']].map(x=>`<div class="rel-row"><b>${x[0]}</b><span>${x[1]}</span><strong>—</strong><i style="width:0"></i><small>pendiente</small></div>`).join('')}
async function loadDiscovery(){try{const d=await api('discover',{region_id:regionId});$('#discovery-title').textContent=d.title;$('#discovery-copy').textContent=d.copy+(d.sample_size?` Muestra: ${Number(d.sample_size).toLocaleString('es-ES')}.`:'');$('#factors').innerHTML=(d.factors||[]).map(f=>`<div class="factor"><span>${f.name}</span><b>${f.value>0?'+':''}${Number(f.value).toFixed(2)}</b><i style="width:${Math.min(100,Math.abs(f.value)*100)}%"></i></div>`).join('')||'<div class="chart-empty">Primero hay que ingerir datos.</div>';$('#hyp-evidence').textContent=d.evidence||'—';$('#dist-strong').textContent=(d.factors||[]).filter(x=>Math.abs(x.value)>=.6).length||'—';$('#dist-mid').textContent=(d.factors||[]).filter(x=>Math.abs(x.value)>=.3&&Math.abs(x.value)<.6).length||'—';$('#dist-weak').textContent=(d.factors||[]).filter(x=>Math.abs(x.value)<.3).length||'—';$('#dist-neg').textContent=(d.factors||[]).filter(x=>x.value<0).length||'—'}catch(e){$('#discovery-title').textContent='Sin datos suficientes'}}
$('#region')?.addEventListener('change',e=>{regionId=e.target.value;customGeometry=null;if(regionId==='custom'){const raw=prompt('Escribe lon_min,lat_min,lon_max,lat_max');const a=(raw||'').split(',').map(Number);if(a.length!==4||a.some(Number.isNaN)){alert('Formato: -75.0,4.0,-74.0,5.0');regionId='alto_xingu';e.target.value=regionId}else customGeometry={type:'bbox',coordinates:a}}loadPlan()});
$('#prepare-zone')?.addEventListener('click',loadPlan);$('#variable')?.addEventListener('change',e=>{$('#map-title').textContent=label(e.target.value);loadMap()});$('#period')?.addEventListener('change',loadMap);$('#hotspots')?.addEventListener('click',e=>{const on=e.currentTarget.classList.toggle('on');e.currentTarget.textContent=on?'Ocultar hotspots':'Mostrar hotspots';document.querySelectorAll('.cell').forEach(c=>c.classList.toggle('hot',on))});$('#lag')?.addEventListener('input',e=>$('#lag-value').textContent=`${e.target.value} meses`);$('#run-relations')?.addEventListener('click',runRelations);$('#refresh-cell')?.addEventListener('click',()=>selectedCell&&selectCell(selectedCell));$('#target')?.addEventListener('change',runRelations);$('#driver')?.addEventListener('change',runRelations);loadWorkspace().then(loadPlan);loadDiscovery();