const PILOT='nora_ingesta_alto_xingu';
const CORE=[
 {id:'ndvi',name:'Vegetación · NDVI',unit:'índice',domain:'vegetation'},
 {id:'precip',name:'Precipitación',unit:'mm/mes',domain:'climate'},
 {id:'temp',name:'Temperatura',unit:'°C',domain:'climate'},
 {id:'water',name:'Agua superficial',unit:'fracción',domain:'water'},
 {id:'fire',name:'Fuego',unit:'fracción quemada',domain:'disturbance'},
 {id:'soil_moisture_rootzone',name:'Humedad de suelo · raíz',unit:'fracción',domain:'soil_water'},
 {id:'lai',name:'Índice de área foliar',unit:'m²/m²',domain:'vegetation'},
 {id:'gpp',name:'Productividad primaria',unit:'kg C/m²/8d',domain:'carbon'},
 {id:'surface_radiation_wm2',name:'Radiación solar',unit:'W/m²',domain:'energy'},
 {id:'wind_speed_ms',name:'Viento',unit:'m/s',domain:'atmosphere'},
 {id:'soc',name:'Carbono orgánico del suelo',unit:'dataset units',domain:'soil'},
 {id:'phh2o',name:'pH del suelo',unit:'dataset units',domain:'soil'},
 {id:'species_occurrence',name:'Observaciones de especies',unit:'registros',domain:'biodiversity'}
];
const MAP_COL={ndvi:'ndvi',precip:'precip_mm',temp:'temp_c',water:'water_fraction',fire:'burned_fraction',soil_moisture_rootzone:'soil_moisture_rootzone',lai:'lai',gpp:'gpp',surface_radiation_wm2:'surface_radiation_wm2',wind_speed_ms:'wind_speed_ms'};
const PILOT_COLS='cell_id,centroid_lon,centroid_lat,year,month,ndvi,precip_mm,temp_c,water_fraction,burned_fraction,soil_moisture_rootzone,lai,gpp,surface_radiation_wm2,wind_speed_ms,soc_0_5cm_mean,phh2o_0_5cm_mean,sand_0_5cm_mean,clay_0_5cm_mean';
function h(){return {apikey:process.env.SUPABASE_SERVICE_ROLE_KEY,Authorization:`Bearer ${process.env.SUPABASE_SERVICE_ROLE_KEY}`,'Content-Type':'application/json'}}
async function db(table,path=''){if(!process.env.SUPABASE_URL)throw new Error('SUPABASE_URL no configurada');const r=await fetch(`${process.env.SUPABASE_URL}/rest/v1/${table}?${path}`,{headers:h()});if(!r.ok)throw new Error(`Supabase ${r.status}: ${await r.text()}`);return r.json()}
function q(s){return encodeURIComponent(s)}
function corr(a,b){const x=[],y=[];for(let i=0;i<a.length;i++)if(Number.isFinite(a[i])&&Number.isFinite(b[i])){x.push(a[i]);y.push(b[i])}if(x.length<12)return null;const ax=x.reduce((s,v)=>s+v,0)/x.length,ay=y.reduce((s,v)=>s+v,0)/y.length;let n=0,dx=0,dy=0;for(let i=0;i<x.length;i++){const u=x[i]-ax,v=y[i]-ay;n+=u*v;dx+=u*u;dy+=v*v}return dx&&dy?n/Math.sqrt(dx*dy):null}
async function getRegions(){return db('nora_regions','select=id,region_id,name,country,region_type,grid_size_deg,active,geometry&active=eq.true&order=id.asc')}
async function getVars(){return db('nora_variables','select=key,name,domain,unit,spatial_resolution,temporal_resolution,source_id&order=domain.asc,key.asc')}
async function getCaps(){return db('nora_source_capabilities','select=source_id,variable_key,access_method,global_coverage,min_year,max_year,spatial_resolution_m,temporal_resolution,priority,quality_notes,official_url&active=eq.true&order=priority.asc')}
async function regionById(id){const rs=await getRegions();return rs.find(r=>r.region_id===id)||null}
async function handler(req,res){try{const {mode='workspace',region_id='alto_xingu',variable='ndvi',period='latest',cell_id}=req.query;
if(mode==='workspace'){const [regions,variables,caps,sources]=await Promise.all([getRegions(),getVars(),getCaps(),db('nora_sources','select=id,name,provider,dataset_id,url&order=id.asc')]);const domains=[...new Set(variables.map(v=>v.domain))];return res.status(200).json({regions,variables,caps,sources,core:CORE,domains,principle:'La zona es una entrada; nunca una limitación. NORA recopila lo disponible y decide qué falta.',stages:['objetivo','zona','variables','recopilación','control de calidad','mapeo','relaciones','robustez','hipótesis','objetivo alcanzado']})}
if(mode==='plan'){const region=await regionById(region_id);const [variables,caps]=await Promise.all([getVars(),getCaps()]);if(!region&&region_id!=='custom')return res.status(404).json({error:'zona no registrada'});const isPilot=region_id==='alto_xingu';const applicable=variables.map(v=>{const cs=caps.filter(c=>c.variable_key===v.key);return {...v,available_sources:cs.length,global:cs.some(c=>c.global_coverage),best_source:cs.sort((a,b)=>a.priority-b.priority)[0]||null}});return res.status(200).json({region:region||{region_id:'custom',name:'Zona personalizada',region_type:'custom'},available:applicable,ingested:isPilot,stage:isPilot?'validate':'detect',objective_reached:false,objective_status:'not_reached',next_action:isPilot?'validar datos piloto':'crear trabajo de recopilación para la zona',note:isPilot?'Piloto completo: 1.880 celdas × 288 meses.':'NORA puede preparar la zona; la ingesta se ejecutará mediante el worker cuando Vercel vuelva a permitir despliegues.'})}
if(mode==='job'){const {zone_key,objective='Explorar el sistema de la zona'}=req.query;const geometry=req.query.geometry||'{}';const rows=await db('nora_zone_jobs',`select=id,zone_key,objective,status,stage,requested_at,started_at,completed_at,variables_found,observations_found,error_message,metadata&zone_key=eq.${q(zone_key||'custom')}&order=requested_at.desc&limit=1`);return res.status(200).json({job:rows[0]||null,objective,geometry})}
if(mode==='sources'){const [caps,sources]=await Promise.all([getCaps(),db('nora_sources','select=id,name,provider,dataset_id,url,description&order=id.asc')]);return res.status(200).json({sources,caps})}
if(mode==='map'){if(region_id!=='alto_xingu')return res.status(200).json({rows:[],status:'not_ingested',message:'Zona preparada. Aún no hay observaciones ingeridas para este territorio.'});const data=await db(PILOT,`select=${q(PILOT_COLS)}&order=year.desc,month.desc,cell_id.asc&limit=1880`);const first=data[0];const latest=first?data.filter(r=>r.year===first.year&&r.month===first.month):[];const key=MAP_COL[variable]||'ndvi';return res.status(200).json({rows:latest,date:first?`${first.year}-${String(first.month).padStart(2,'0')}`:null,cell_count:latest.length,total_rows:data.length,variable:key,status:'ready',resolution:'0.1°'})}
if(mode==='cell'){if(region_id!=='alto_xingu'||!cell_id)return res.status(200).json({rows:[],status:'not_ingested'});const data=await db(PILOT,`select=${q(PILOT_COLS)}&cell_id=eq.${q(cell_id)}&order=year.asc,month.asc&limit=500`);const nd=data.map(r=>Number(r.ndvi)),rain=data.map(r=>Number(r.precip_mm));let best={r:-Infinity,lag:0};for(let lag=0;lag<=6;lag++){const r=corr(rain.slice(0,-lag||undefined),nd.slice(lag));if(r!=null&&r>best.r)best={r,lag}}return res.status(200).json({rows:data,relation:{label:'Precipitación → NDVI',r:Number.isFinite(best.r)?best.r:null,lag:best.lag},trend:{label:nd.length>1?`${nd.at(-1)>=nd[0]?'↑':'↓'} ${Math.abs(nd.at(-1)-nd[0]).toFixed(2)}`:'pendiente'},status:'ready'})}
if(mode==='relations'){if(region_id!=='alto_xingu')return res.status(200).json({lags:[],best:null,cells:0,status:'not_ingested'});const target=String(req.query.target||'ndvi'),driver=String(req.query.driver||'precip'),tc=MAP_COL[target]||'ndvi',dc=MAP_COL[driver]||'precip_mm';const data=await db(PILOT,`select=cell_id,year,month,${tc},${dc}&order=cell_id.asc,year.asc,month.asc&limit=60000`);const cells=[...new Set(data.map(r=>r.cell_id))],lags=[];for(let lag=0;lag<=6;lag++){const rs=[];for(const c of cells.slice(0,200)){const s=data.filter(r=>r.cell_id===c),a=s.map(r=>Number(r[dc])),b=s.map(r=>Number(r[tc])),r=corr(a.slice(0,-lag||undefined),b.slice(lag));if(r!=null)rs.push(r)}lags.push(rs.length?rs.reduce((a,b)=>a+b,0)/rs.length:0)}const best=lags.reduce((o,v,i)=>v>o.r?{r:v,lag:i}:o,{r:-Infinity,lag:0});return res.status(200).json({lags,best:best.r>-Infinity?best:null,cells:Math.min(cells.length,200),sampled:cells.length>200,status:'ready'})}
if(mode==='discover'){if(region_id!=='alto_xingu')return res.status(200).json({status:'not_ingested',title:'Zona preparada, sin resultados inventados.',copy:'NORA necesita ingerir y validar los datos de esta zona antes de mostrar un patrón.',factors:[]});const data=await db(PILOT,`select=ndvi,precip_mm,temp_c,water_fraction,burned_fraction,soc_0_5cm_mean,phh2o_0_5cm_mean,sand_0_5cm_mean,clay_0_5cm_mean&limit=60000`);const y=data.map(r=>Number(r.ndvi));const candidates=[['Precipitación','precip_mm'],['Temperatura','temp_c'],['Agua','water_fraction'],['Fuego','burned_fraction'],['SOC','soc_0_5cm_mean'],['pH','phh2o_0_5cm_mean'],['Arena','sand_0_5cm_mean'],['Arcilla','clay_0_5cm_mean']];const factors=candidates.map(([name,k])=>({name,value:corr(data.map(r=>Number(r[k])),y)})).filter(x=>x.value!=null).sort((a,b)=>Math.abs(b.value)-Math.abs(a.value));return res.status(200).json({status:'exploratory',title:factors[0]?`Señal principal: ${factors[0].name}`:'Sin evidencia suficiente',copy:'Asociación exploratoria calculada sobre el piloto; todavía no es causalidad ni un descubrimiento confirmado.',factors:factors.slice(0,8),sample_size:data.length,evidence:factors[0]?'calculado':'insuficiente'})}
return res.status(400).json({error:'mode no soportado'})}catch(e){return res.status(500).json({error:e.message})}}
module.exports=handler;