const TABLE='nora_ingesta_alto_xingu';
const cols='cell_id,centroid_lon,centroid_lat,year,month,ndvi,precip_mm,temp_c,water_fraction,burned_fraction,soc_0_5cm_mean,phh2o_0_5cm_mean,sand_0_5cm_mean,clay_0_5cm_mean';
const coreCatalog=[
 {id:'ndvi',name:'Vegetación · NDVI',unit:'índice',domain:'vegetation'},
 {id:'precip',name:'Precipitación',unit:'mm/mes',domain:'climate'},
 {id:'temp',name:'Temperatura',unit:'°C',domain:'climate'},
 {id:'water',name:'Agua superficial',unit:'fracción',domain:'water'},
 {id:'fire',name:'Fuego',unit:'fracción quemada',domain:'disturbance'},
 {id:'soc',name:'Carbono orgánico del suelo',unit:'SOC',domain:'soil'},
 {id:'ph',name:'pH del suelo',unit:'pH',domain:'soil'},
 {id:'sand',name:'Arena del suelo',unit:'%',domain:'soil'},
 {id:'clay',name:'Arcilla del suelo',unit:'%',domain:'soil'}
];
function headers(){return {'apikey':process.env.SUPABASE_SERVICE_ROLE_KEY,'Authorization':`Bearer ${process.env.SUPABASE_SERVICE_ROLE_KEY}`,'Content-Type':'application/json'}}
async function db(table,path=''){const base=process.env.SUPABASE_URL;if(!base)throw new Error('SUPABASE_URL no configurada en Vercel');const r=await fetch(`${base}/rest/v1/${table}?${path}`,{headers:headers()});if(!r.ok)throw new Error(`Supabase ${r.status}: ${await r.text()}`);return r.json()}
function corr(a,b){const x=[],y=[];for(let i=0;i<a.length;i++)if(Number.isFinite(a[i])&&Number.isFinite(b[i])){x.push(a[i]);y.push(b[i])}if(x.length<12)return null;const ax=x.reduce((s,v)=>s+v,0)/x.length,ay=y.reduce((s,v)=>s+v,0)/y.length;let n=0,dx=0,dy=0;for(let i=0;i<x.length;i++){const u=x[i]-ax,v=y[i]-ay;n+=u*v;dx+=u*u;dy+=v*v}return dx&&dy?n/Math.sqrt(dx*dy):null}
function col(id){return {ndvi:'ndvi',precip:'precip_mm',temp:'temp_c',water:'water_fraction',fire:'burned_fraction',soc:'soc_0_5cm_mean',ph:'phh2o_0_5cm_mean',sand:'sand_0_5cm_mean',clay:'clay_0_5cm_mean'}[id]}
async function regions(){return db('nora_regions','select=id,region_id,name,country,region_type,grid_size_deg,active,geometry&active=eq.true&order=id.asc')}
async function variables(){return db('nora_variables','select=key,name,domain,unit,spatial_resolution,temporal_resolution&order=domain.asc,key.asc')}
async function handler(req,res){try{const {mode='map',variable='ndvi',period='latest',cell_id,region_id='alto_xingu'}=req.query;
if(mode==='workspace'){const [rs,vs]=await Promise.all([regions(),variables()]);return res.status(200).json({regions:rs,variables:vs,core:coreCatalog,objective:'Descubrir relaciones robustas y verificables, no simplemente encontrar correlaciones.',stages:['Definir objetivo','Detectar variables disponibles','Recopilar datos','Validar calidad','Explorar relaciones','Probar robustez','Generar hipótesis','Comprobar si el objetivo está alcanzado']})}
if(mode==='plan'){const [rs,vs]=await Promise.all([regions(),variables()]);const region=rs.find(r=>r.region_id===region_id)||rs[0];const available=vs.map(v=>({...v,collection:'global'}));const pilot=region?.region_id==='alto_xingu';return res.status(200).json({region,available,ready:!!region,ingested:pilot,ingested_note:pilot?'Datos piloto completos: 1.880 celdas × 288 meses.':'Zona registrada; la recopilación debe ejecutarse antes de mostrar resultados.',next:pilot?'analizar':'collect'})}
if(mode==='catalog'){const [vs,rs]=await Promise.all([variables(),regions()]);return res.status(200).json({territory:region_id,regions:rs,variables:vs,core:coreCatalog})}
if(mode==='map'){if(region_id!=='alto_xingu')return res.status(200).json({rows:[],date:null,cell_count:0,total_rows:0,variables:coreCatalog.length,status:'not_ingested',message:'Zona preparada, pero todavía no hay datos ingeridos.'});let p='select='+encodeURIComponent(cols)+'&order=year.desc,month.desc,cell_id.asc&limit=1880';if(period==='2024')p+='&year=eq.2024';if(period==='2019')p+='&year=gte.2019';if(period==='2001')p+='&year=gte.2001';const data=await db(TABLE,p);const first=data[0];const latest=data.filter(r=>r.year===first?.year&&r.month===first?.month);return res.status(200).json({rows:latest,date:first?`${first.year}-${String(first.month).padStart(2,'0')}`:null,cell_count:latest.length,total_rows:data.length,variables:coreCatalog.length,status:'ready'})}
if(mode==='cell'){if(region_id!=='alto_xingu')return res.status(200).json({rows:[],relation:{label:'Datos todavía no recopilados',r:null,lag:null},trend:{label:'pendiente'}});if(cell_id==null)throw new Error('cell_id requerido');const data=await db(TABLE,`select=${encodeURIComponent(cols)}&cell_id=eq.${encodeURIComponent(cell_id)}&order=year.asc,month.asc&limit=500`);const nd=data.map(r=>Number(r.ndvi)),p=data.map(r=>Number(r.precip_mm));let best={r:-Infinity,lag:0};for(let lag=0;lag<=6;lag++){const r=corr(p.slice(0,-lag||undefined),nd.slice(lag));if(r!=null&&r>best.r)best={r,lag}}const change=Number(nd.at(-1))-Number(nd[0]);return res.status(200).json({rows:data,relation:{label:'Precipitación → NDVI',r:Number.isFinite(best.r)?best.r:null,lag:best.lag},trend:{label:`${change>=0?'↑':'↓'} ${Math.abs(change).toFixed(2)}`}})}
if(mode==='relations'){const target=String(req.query.target||'ndvi'),driver=String(req.query.driver||'precip');if(region_id!=='alto_xingu')return res.status(200).json({lags:[],best:null,sampled:false,cells:0,target,driver,status:'not_ingested'});const targetCol=col(target)||'ndvi',driverCol=col(driver)||'precip_mm';let p=`select=cell_id,year,month,${targetCol},${driverCol}&order=cell_id.asc,year.asc,month.asc&limit=60000`;if(cell_id)p+=`&cell_id=eq.${encodeURIComponent(cell_id)}`;const data=await db(TABLE,p),cells=[...new Set(data.map(r=>r.cell_id))],lags=[];for(let lag=0;lag<=6;lag++){const rs=[];for(const c of cells.slice(0,200)){const s=data.filter(r=>r.cell_id===c),a=s.map(r=>Number(r[driverCol])),b=s.map(r=>Number(r[targetCol])),r=corr(a.slice(0,-lag||undefined),b.slice(lag));if(r!=null)rs.push(r)}lags.push(rs.length?rs.reduce((a,b)=>a+b,0)/rs.length:0)}const best=lags.reduce((o,v,i)=>v>o.r?{r:v,lag:i}:o,{r:-Infinity,lag:0});return res.status(200).json({lags,best:best.r>-Infinity?best:null,sampled:cells.length>200,cells:Math.min(cells.length,200),target,driver,status:'ready'})}
if(mode==='discover'){if(region_id!=='alto_xingu')return res.status(200).json({title:'Esta zona está preparada para NORA.',copy:'Primero recopilaré automáticamente las variables compatibles con la zona y después iniciaré el descubrimiento. No se muestran resultados sin datos.',distribution:{strong:'—',moderate:'—',weak:'—',negative:'—'},factors:[],evidence:'sin datos',sample_size:0,status:'not_ingested'});const data=await db(TABLE,`select=year,month,ndvi,precip_mm,temp_c,water_fraction,burned_fraction,soc_0_5cm_mean,phh2o_0_5cm_mean,sand_0_5cm_mean,clay_0_5cm_mean&order=year.asc,month.asc&limit=60000`);const target=data.map(r=>Number(r.ndvi));const candidates=[['Precipitación','precip_mm'],['Temperatura','temp_c'],['Agua','water_fraction'],['Fuego','burned_fraction'],['SOC','soc_0_5cm_mean'],['pH','phh2o_0_5cm_mean'],['Arena','sand_0_5cm_mean'],['Arcilla','clay_0_5cm_mean']];const factors=candidates.map(([name,k])=>({name,value:corr(data.map(r=>Number(r[k])),target)})).filter(x=>x.value!=null).sort((a,b)=>Math.abs(b.value)-Math.abs(a.value));const top=factors[0];return res.status(200).json({title:top?`La señal de NDVI presenta su asociación más fuerte con ${top.name}.`:'No hay evidencia suficiente para destacar una relación.',copy:'Resultado calculado sobre datos de NORA. Es exploratorio: asociación no implica causalidad.',distribution:{strong:factors.filter(x=>Math.abs(x.value)>=.6).length,moderate:factors.filter(x=>Math.abs(x.value)>=.3&&Math.abs(x.value)<.6).length,weak:factors.filter(x=>Math.abs(x.value)<.3).length,negative:factors.filter(x=>x.value<0).length},factors:factors.slice(0,6),evidence:top?'calculado · exploratorio':'insuficiente',sample_size:data.length,status:'ready'})}
return res.status(400).json({error:'mode no soportado'})}catch(e){return res.status(500).json({error:e.message})}}
module.exports=handler;