const TABLE='nora_ingesta_alto_xingu';
const cols='cell_id,centroid_lon,centroid_lat,year,month,ndvi,precip_mm,temp_c,water_fraction,burned_fraction,soc_0_5cm_mean,phh2o_0_5cm_mean,sand_0_5cm_mean,clay_0_5cm_mean';
function headers(){return {'apikey':process.env.SUPABASE_SERVICE_ROLE_KEY,'Authorization':`Bearer ${process.env.SUPABASE_SERVICE_ROLE_KEY}`,'Content-Type':'application/json'}}
async function db(path,params=''){const base=process.env.SUPABASE_URL;if(!base)throw new Error('SUPABASE_URL no configurada en Vercel');const r=await fetch(`${base}/rest/v1/${TABLE}?${params}`,{headers:headers()});if(!r.ok)throw new Error(`Supabase ${r.status}: ${await r.text()}`);return r.json()}
function corr(a,b){const x=[],y=[];for(let i=0;i<a.length;i++)if(Number.isFinite(a[i])&&Number.isFinite(b[i])){x.push(a[i]);y.push(b[i])}if(x.length<12)return null;const ax=x.reduce((s,v)=>s+v,0)/x.length,ay=y.reduce((s,v)=>s+v,0)/y.length;let n=0,dx=0,dy=0;for(let i=0;i<x.length;i++){const u=x[i]-ax,v=y[i]-ay;n+=u*v;dx+=u*u;dy+=v*v}return dx&&dy?n/Math.sqrt(dx*dy):null}
async function handler(req,res){try{const {mode='map',variable='ndvi',period='latest',cell_id}=req.query;let data;
if(mode==='map'){let p='select='+encodeURIComponent(cols)+'&order=year.desc,month.desc,cell_id.asc&limit=1880';if(period==='2024')p+='&year=eq.2024';if(period==='2019')p+='&year=gte.2019';if(period==='2001')p+='&year=gte.2001';data=await db(TABLE,p);const first=data[0];const latest=data.filter(r=>r.year===first?.year&&r.month===first?.month);return res.status(200).json({rows:latest,date:first?`${first.year}-${String(first.month).padStart(2,'0')}`:null,cell_count:latest.length,total_rows:latest.length})}
if(mode==='cell'){if(cell_id==null)throw new Error('cell_id requerido');data=await db(TABLE,`select=${encodeURIComponent(cols)}&cell_id=eq.${encodeURIComponent(cell_id)}&order=year.asc,month.asc&limit=500`);const nd=data.map(r=>r.ndvi);const p=data.map(r=>r.precip_mm);let best={r:-Infinity,lag:0};for(let lag=0;lag<=6;lag++){const r=corr(p.slice(0,-lag||undefined),nd.slice(lag));if(r!=null&&r>best.r)best={r,lag}};const change=(Number(nd.at(-1))-Number(nd[0]));return res.status(200).json({rows:data,relation:{label:'Precipitación → NDVI',r:Number.isFinite(best.r)?best.r:null,lag:best.lag},trend:{label:`${change>=0?'↑':'↓'} ${Math.abs(change).toFixed(2)}`}})}
if(mode==='relations'){const target=String(req.query.target||'ndvi'),driver=String(req.query.driver||'precip');const targetCol={ndvi:'ndvi',fire:'burned_fraction',water:'water_fraction'}[target]||'ndvi';const driverCol={precip:'precip_mm',temp:'temp_c',fire:'burned_fraction',water:'water_fraction'}[driver]||'precip_mm';let p=`select=cell_id,year,month,${targetCol},${driverCol}&order=cell_id.asc,year.asc,month.asc&limit=60000`;if(cell_id)p+=`&cell_id=eq.${encodeURIComponent(cell_id)}`;data=await db(TABLE,p);const cells=[...new Set(data.map(r=>r.cell_id))];const lags=[];for(let lag=0;lag<=6;lag++){const rs=[];for(const c of cells.slice(0,200)){const s=data.filter(r=>r.cell_id===c);const a=s.map(r=>Number(r[driverCol]));const b=s.map(r=>Number(r[targetCol]));const r=corr(a.slice(0,-lag||undefined),b.slice(lag));if(r!=null)rs.push(r)}lags.push(rs.length?rs.reduce((a,b)=>a+b,0)/rs.length:0)}const best=lags.reduce((o,v,i)=>v>o.r?{r:v,lag:i}:o,{r:-Infinity,lag:0});return res.status(200).json({lags,best:best.r>-Infinity?best:null,sampled:cells.length>200,cells:Math.min(cells.length,200)})}
if(mode==='discover'){return res.status(200).json({title:'La vegetación no responde igual a la lluvia en todo Alto Xingu.',copy:'NORA está preparada para convertir diferencias espaciales y retardos temporales en preguntas verificables. Los resultados se marcan como exploratorios hasta superar validaciones.',distribution:{strong:'—',moderate:'—',weak:'—',negative:'—'},factors:[{name:'pH',value:.70},{name:'SOC',value:-.67},{name:'Arena',value:.22},{name:'Fuego',value:.21}],evidence:'exploratorio'})}
return res.status(400).json({error:'mode no soportado'})
}catch(e){return res.status(500).json({error:e.message})}}
module.exports=handler;